#!/usr/bin/env bash
# tool/zenodo/deposit.sh
#
# [DEPRECATED 2026-04-29] papers/.own own 9 (papers-cross-repo-publish-canonical, papers@6b670f9)
# sister repo 자체 zenodo publish 도구 금지 — papers CLI 위임 mandate.
# 본 스크립트는 active hexa-weave w2 paper deposit 용으로 grandfather 유지.
# 신규 paper 는 반드시 papers CLI 사용:
#   papers publish <paper-id> --target zenodo --sandbox --dry-run
#   papers publish <paper-id> --target all
# 검증: papers cross-repo-lint --report (이 파일 BLOCK 표시 grandfather note)
# 향후 hexa-weave w2 publish 완료 후 archive/_deprecated/ 이동 예정.
#
# HEXA-WEAVE Zenodo deposit auto-script (cycle 14 deposit-prep).
#
# raw 65/68: idempotent. Re-running this script with the same
# DEPOSITION_ID (cached in tool/zenodo/.deposition_id) re-uses the
# existing deposition instead of creating a new one. The PUBLISH step
# remains commented out and never runs without an explicit user
# uncomment AND re-invocation with --i-have-read-the-irreversibility-warning.
#
# Pre-conditions enforced at top:
#   - ZENODO_TOKEN env var set (do NOT hard-code).
#   - tool/zenodo/metadata.json exists and ALL "PENDING_USER_INPUT"
#     placeholders have been replaced (lint check).
#   - papers/hexa-weave-formal-mechanical-w2-2026-04-28.pdf exists.
#   - tool/zenodo/manifest.sha256 exists (regenerated by gen_manifest.sh).
#
# Steps 1-4 are reversible (the deposition can be discarded via
# DELETE before publish). Step 5 (publish) is irreversible and is
# commented out. The user must explicitly un-comment step 5 in a
# separate edit AND re-run with the consent flag.
#
# Usage:
#   export ZENODO_TOKEN=<sandbox-or-production-token>
#   bash tool/zenodo/deposit.sh                            # steps 1-4 dry-run preflight only
#   bash tool/zenodo/deposit.sh --upload                   # steps 1-4 actual upload (still reversible)
#   bash tool/zenodo/deposit.sh --upload --i-have-read-the-irreversibility-warning  # only path that may un-comment step 5
#
# Exit codes:
#   0  preflight PASS or upload PASS (steps 1-4)
#   1  pre-condition failed (ZENODO_TOKEN missing, PDF missing, etc.)
#   2  network / HTTP failure during upload
#   3  publish requested without irreversibility flag

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ZENODO_DIR="${REPO_ROOT}/tool/zenodo"
PDF_PATH="${REPO_ROOT}/papers/hexa-weave-formal-mechanical-w2-2026-04-28.pdf"
TARBALL_PATH="${ZENODO_DIR}/lean4-n6-mechverif-cycle12.tar.gz"
METADATA_JSON="${ZENODO_DIR}/metadata.json"
MANIFEST_SHA="${ZENODO_DIR}/manifest.sha256"
DEPOSITION_ID_CACHE="${ZENODO_DIR}/.deposition_id"

# Default to Zenodo SANDBOX (https://sandbox.zenodo.org) for the first run.
# Production Zenodo (https://zenodo.org) is opt-in via ZENODO_API=production.
ZENODO_API_HOST="${ZENODO_API_HOST:-https://sandbox.zenodo.org}"

UPLOAD=0
IRREVERSIBILITY_FLAG=0
for arg in "$@"; do
  case "$arg" in
    --upload) UPLOAD=1 ;;
    --i-have-read-the-irreversibility-warning) IRREVERSIBILITY_FLAG=1 ;;
    --help|-h)
      sed -n '1,40p' "${BASH_SOURCE[0]}"
      exit 0
      ;;
  esac
done

# ----------------------------------------------------------------------
# pre-condition: ZENODO_TOKEN
# ----------------------------------------------------------------------
if [[ -z "${ZENODO_TOKEN:-}" ]]; then
  echo "FAIL: ZENODO_TOKEN env var is not set." >&2
  echo "  export ZENODO_TOKEN=<your-zenodo-personal-access-token>" >&2
  echo "  (sandbox.zenodo.org tokens for dry-runs; zenodo.org tokens for production.)" >&2
  exit 1
fi

# ----------------------------------------------------------------------
# pre-condition: metadata.json has no PENDING placeholders
# ----------------------------------------------------------------------
if grep -q "PENDING_USER_INPUT" "$METADATA_JSON"; then
  echo "FAIL: metadata.json contains PENDING_USER_INPUT placeholders." >&2
  echo "  Resolve all 5 user-decision items in" >&2
  echo "  proposals/hexa_weave_zenodo_auto_prep_2026_04_28.md §4 first," >&2
  echo "  then edit ${METADATA_JSON} to fill the PENDING fields." >&2
  exit 1
fi

# ----------------------------------------------------------------------
# pre-condition: PDF + tarball + manifest exist
# ----------------------------------------------------------------------
for f in "$PDF_PATH" "$TARBALL_PATH" "$MANIFEST_SHA"; do
  if [[ ! -f "$f" ]]; then
    echo "FAIL: required file missing: $f" >&2
    if [[ "$f" == "$PDF_PATH" ]]; then
      echo "  Compile the paper to PDF (e.g. pandoc papers/hexa-weave-formal-mechanical-w2-2026-04-28.md -o $f)." >&2
    elif [[ "$f" == "$TARBALL_PATH" ]]; then
      echo "  Generate the Lean source tarball: bash tool/zenodo/gen_tarball.sh" >&2
    elif [[ "$f" == "$MANIFEST_SHA" ]]; then
      echo "  Generate the SHA-256 manifest: bash tool/zenodo/gen_manifest.sh" >&2
    fi
    exit 1
  fi
done

# ----------------------------------------------------------------------
# pre-condition: irreversibility flag without --upload is meaningless
# ----------------------------------------------------------------------
if [[ "$IRREVERSIBILITY_FLAG" -eq 1 && "$UPLOAD" -eq 0 ]]; then
  echo "FAIL: --i-have-read-the-irreversibility-warning requires --upload." >&2
  exit 3
fi

echo "[deposit.sh] pre-flight PASS"
echo "  ZENODO_API_HOST = ${ZENODO_API_HOST}"
echo "  PDF             = ${PDF_PATH}"
echo "  Lean tarball    = ${TARBALL_PATH}"
echo "  metadata.json   = ${METADATA_JSON}"
echo "  manifest.sha256 = ${MANIFEST_SHA}"
echo "  UPLOAD          = ${UPLOAD}"
echo "  PUBLISH         = 0 (always; step 5 is commented out)"

if [[ "$UPLOAD" -eq 0 ]]; then
  echo "[deposit.sh] dry-run only (use --upload to actually call Zenodo API)."
  exit 0
fi

# ----------------------------------------------------------------------
# Step 1: create or re-use deposition (idempotent)
# ----------------------------------------------------------------------
if [[ -s "$DEPOSITION_ID_CACHE" ]]; then
  DEP_ID="$(cat "$DEPOSITION_ID_CACHE")"
  echo "[deposit.sh] re-using cached deposition id: ${DEP_ID}"
  DEP_RESPONSE="$(curl -fsSL \
    -H "Authorization: Bearer $ZENODO_TOKEN" \
    -X GET \
    "${ZENODO_API_HOST}/api/deposit/depositions/${DEP_ID}")"
else
  echo "[deposit.sh] creating new deposition..."
  DEP_RESPONSE="$(curl -fsSL \
    -H "Authorization: Bearer $ZENODO_TOKEN" \
    -H "Content-Type: application/json" \
    -X POST \
    -d "{}" \
    "${ZENODO_API_HOST}/api/deposit/depositions")"
  DEP_ID="$(echo "$DEP_RESPONSE" | jq -r '.id')"
  echo "$DEP_ID" > "$DEPOSITION_ID_CACHE"
  echo "[deposit.sh] new deposition id: ${DEP_ID} (cached to ${DEPOSITION_ID_CACHE})"
fi
BUCKET="$(echo "$DEP_RESPONSE" | jq -r '.links.bucket')"

# ----------------------------------------------------------------------
# Step 2: upload PDF (idempotent: PUT replaces if file exists)
# ----------------------------------------------------------------------
echo "[deposit.sh] uploading PDF..."
curl -fsSL \
  -H "Authorization: Bearer $ZENODO_TOKEN" \
  -H "Content-Type: application/octet-stream" \
  -X PUT \
  --data-binary "@${PDF_PATH}" \
  "${BUCKET}/$(basename "$PDF_PATH")" > /dev/null

# ----------------------------------------------------------------------
# Step 3: upload Lean source tarball (idempotent)
# ----------------------------------------------------------------------
echo "[deposit.sh] uploading Lean source tarball..."
curl -fsSL \
  -H "Authorization: Bearer $ZENODO_TOKEN" \
  -H "Content-Type: application/octet-stream" \
  -X PUT \
  --data-binary "@${TARBALL_PATH}" \
  "${BUCKET}/$(basename "$TARBALL_PATH")" > /dev/null

# ----------------------------------------------------------------------
# Step 3.5: upload SHA-256 manifest (deposit-side reviewer aid)
# ----------------------------------------------------------------------
echo "[deposit.sh] uploading SHA-256 manifest..."
curl -fsSL \
  -H "Authorization: Bearer $ZENODO_TOKEN" \
  -H "Content-Type: application/octet-stream" \
  -X PUT \
  --data-binary "@${MANIFEST_SHA}" \
  "${BUCKET}/$(basename "$MANIFEST_SHA")" > /dev/null

# ----------------------------------------------------------------------
# Step 4: attach metadata (idempotent: PUT replaces full doc)
# ----------------------------------------------------------------------
echo "[deposit.sh] attaching metadata..."
# Strip the leading underscore-prefixed annotation keys so Zenodo
# accepts the doc. jq filter: keep only "metadata".
jq '{ metadata: .metadata }' "$METADATA_JSON" > "${ZENODO_DIR}/.metadata.payload.json"
curl -fsSL \
  -H "Authorization: Bearer $ZENODO_TOKEN" \
  -H "Content-Type: application/json" \
  -X PUT \
  -d "@${ZENODO_DIR}/.metadata.payload.json" \
  "${ZENODO_API_HOST}/api/deposit/depositions/${DEP_ID}" > /dev/null
rm -f "${ZENODO_DIR}/.metadata.payload.json"

echo "[deposit.sh] steps 1-4 PASS (deposition id ${DEP_ID})."
echo "[deposit.sh] review the staged deposit at:"
echo "  ${ZENODO_API_HOST}/deposit/${DEP_ID}"
echo
echo "If everything looks correct, the user may un-comment Step 5 below"
echo "AND re-run with --upload --i-have-read-the-irreversibility-warning."
echo "Step 5 is IRREVERSIBLE: the DOI is minted and the deposition cannot"
echo "be deleted (only superseded by a new version)."

# ----------------------------------------------------------------------
# Step 5 (PUBLISH; IRREVERSIBLE; COMMENTED OUT BY DEFAULT)
# ----------------------------------------------------------------------
# Un-comment the block below ONLY after:
#   (a) the user has visually reviewed the staged deposit on the Zenodo
#       web UI (URL printed above),
#   (b) the user has explicitly typed approval to a Claude session AND
#       the session has logged the approval in mk-history,
#   (c) the user has invoked deposit.sh with both --upload and
#       --i-have-read-the-irreversibility-warning.
#
# if [[ "$IRREVERSIBILITY_FLAG" -eq 1 ]]; then
#   echo "[deposit.sh] PUBLISHING (IRREVERSIBLE)..."
#   PUBLISH_RESPONSE="$(curl -fsSL \
#     -H "Authorization: Bearer $ZENODO_TOKEN" \
#     -X POST \
#     "${ZENODO_API_HOST}/api/deposit/depositions/${DEP_ID}/actions/publish")"
#   DOI="$(echo "$PUBLISH_RESPONSE" | jq -r '.doi')"
#   echo "[deposit.sh] DOI minted: ${DOI}"
#   echo "$DOI" > "${ZENODO_DIR}/.doi"
# else
#   echo "[deposit.sh] step 5 skipped (no irreversibility flag)."
# fi

exit 0
