#!/usr/bin/env bash
# tool/atlas_status_all.sh — meta-status aggregator for all bash atlas tools (2026-04-26)
#
# 단일 명령으로 atlas family 전체 상태 한 페이지 — runtime-check + search-stats +
# dashboard + diff-per-type + precommit 일괄 실행.
# self-host 회피 (bash + 다른 bash tools 만, no hexa dep).
#
# usage: tool/atlas_status_all.sh [--brief|--full]
#   --brief  핵심 sentinel 만 (default)
#   --full   각 도구 전체 출력
#
# exit codes: 0 = all PASS, 1 = usage, 2 = any tool FAIL
# sentinel: __ATLAS_STATUS_ALL__ runtime=<S> dashboard_h=<H/R> facts=<F> staged_atlas=<A>
# origin: meta-tool aggregating Tier-1+2 bash tools (i2/i8/i9/i13/i14)

set -uo pipefail

NEXUS_ROOT="${NEXUS_ROOT:-$HOME/core/nexus}"
TOOL_DIR="$NEXUS_ROOT/tool"

MODE="brief"
case "${1:-}" in
    --full) MODE="full" ;;
    --brief|"") MODE="brief" ;;
    --help|-h)
        echo "usage: $0 [--brief|--full]"
        echo "  --brief  핵심 sentinel 만 + summary (default)"
        echo "  --full   각 도구 전체 출력"
        exit 0
        ;;
    *) echo "unknown: $1" >&2; exit 1 ;;
esac

NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "═════════════════════════════════════════════════════════════"
echo "  ATLAS STATUS ALL — $NOW (UTC)"
echo "  generated by tool/atlas_status_all.sh ($MODE)"
echo "═════════════════════════════════════════════════════════════"

# ─── 1. hexa runtime ─────────────────────────────────────────
echo ""
echo "▶ 1. hexa runtime (i2)"
RUNTIME_OUT=$("$TOOL_DIR/hexa_runtime_check.sh" 2>&1 || true)
RUNTIME_LAST=$(echo "$RUNTIME_OUT" | tail -1)
if [ "$MODE" = "full" ]; then echo "$RUNTIME_OUT"; else echo "  $RUNTIME_LAST"; fi
RUNTIME_STATUS=$(echo "$RUNTIME_LAST" | sed -nE 's/.*stage=([0-9]+).*/stage_\1/p')
[ -z "$RUNTIME_STATUS" ] && RUNTIME_STATUS="unknown"
RUNTIME_HEALTHY="0"
echo "$RUNTIME_LAST" | grep -q "PASS" && RUNTIME_HEALTHY="1"

# ─── 2. atlas search stats ───────────────────────────────────
echo ""
echo "▶ 2. atlas search stats (i8)"
STATS_OUT=$(bash "$TOOL_DIR/atlas_search.sh" --stats 2>&1 || true)
if [ "$MODE" = "full" ]; then
    echo "$STATS_OUT"
else
    echo "$STATS_OUT" | grep -E "^[0-9]+ @|^__ATLAS_SEARCH__" | head -12
fi
STATS_TOTAL=$(echo "$STATS_OUT" | grep -oE "total_entries=[0-9]+" | cut -d= -f2)
[ -z "$STATS_TOTAL" ] && STATS_TOTAL=0
STATS_SHARDS=$(echo "$STATS_OUT" | grep -oE "shards=[0-9]+" | cut -d= -f2)
[ -z "$STATS_SHARDS" ] && STATS_SHARDS=0

# ─── 3. cross-repo dashboard ─────────────────────────────────
echo ""
echo "▶ 3. cross-repo dashboard (i13)"
DASHBOARD_OUT=$(bash "$TOOL_DIR/atlas_cross_repo_dashboard.sh" --text 2>&1 || true)
if [ "$MODE" = "full" ]; then echo "$DASHBOARD_OUT"; else
    echo "$DASHBOARD_OUT" | grep -E "honesty=|__ATLAS_CROSS_REPO" | head -6
fi
DASHBOARD_HONESTY=$(echo "$DASHBOARD_OUT" | grep -oE "honesty_pass=[0-9]+/[0-9]+" | cut -d= -f2)
[ -z "$DASHBOARD_HONESTY" ] && DASHBOARD_HONESTY="0/0"
DASHBOARD_FACTS=$(echo "$DASHBOARD_OUT" | grep -oE "total_facts=[0-9]+" | cut -d= -f2)
[ -z "$DASHBOARD_FACTS" ] && DASHBOARD_FACTS=0

# ─── 4. recent atlas diffs ───────────────────────────────────
echo ""
echo "▶ 4. recent atlas changes (i9)"
DIFF_OUT=$(bash "$TOOL_DIR/atlas_diff_per_type.sh" --recent 5 2>&1 || true)
if [ "$MODE" = "full" ]; then echo "$DIFF_OUT"; else
    echo "$DIFF_OUT" | grep -E "^[a-f0-9]{7,}|^__ATLAS_DIFF" | head -6
fi
DIFF_COMMITS=$(echo "$DIFF_OUT" | grep -oE "commits=[0-9]+" | cut -d= -f2)
[ -z "$DIFF_COMMITS" ] && DIFF_COMMITS=0
DIFF_ADD=$(echo "$DIFF_OUT" | grep -oE "additions=[0-9]+" | cut -d= -f2)
[ -z "$DIFF_ADD" ] && DIFF_ADD=0

# ─── 5. precommit (staged check) ────────────────────────────
echo ""
echo "▶ 5. precommit staged check (i14)"
PRECOMMIT_OUT=$(bash "$TOOL_DIR/atlas_precommit_check.sh" 2>&1 || true)
if [ "$MODE" = "full" ]; then echo "$PRECOMMIT_OUT"; else
    echo "$PRECOMMIT_OUT" | tail -3
fi
PRECOMMIT_STAGED=$(echo "$PRECOMMIT_OUT" | grep -oE "added=[0-9]+" | cut -d= -f2)
[ -z "$PRECOMMIT_STAGED" ] && PRECOMMIT_STAGED=0

# ─── 6. cross-shard collision (dedup audit followup) ─────────
echo ""
echo "▶ 6. cross-shard collision watchdog"
COLLISION_OUT=$(bash "$TOOL_DIR/atlas_cross_shard_collision.sh" 2>&1 || true)
if [ "$MODE" = "full" ]; then echo "$COLLISION_OUT"; else
    echo "$COLLISION_OUT" | grep -E "HARMLESS_DUP|CONFLICT|__ATLAS_CROSS_SHARD_COLLISION__" | head -4
fi
COLLISION_DUP=$(echo "$COLLISION_OUT" | grep -oE "dup=[0-9]+" | head -1 | cut -d= -f2)
[ -z "$COLLISION_DUP" ] && COLLISION_DUP=0
COLLISION_CONF=$(echo "$COLLISION_OUT" | grep -oE "conflict=[0-9]+" | head -1 | cut -d= -f2)
[ -z "$COLLISION_CONF" ] && COLLISION_CONF=0

# ─── 7. defense system (R1 cmd_sha256 + bridge_sha256 + R3-full hook + R4 rotation) ───
echo ""
echo "▶ 7. defense system (R1/R3/R4 — Ω-cycle 2026-04-26)"
DEF_FAL_SHA="missing"
if [ -f "$NEXUS_ROOT/state/falsifier_registry.sha256" ]; then
    DEF_FAL_SHA=$(cut -c1-12 "$NEXUS_ROOT/state/falsifier_registry.sha256" 2>/dev/null | head -1)
    [ -z "$DEF_FAL_SHA" ] && DEF_FAL_SHA="empty"
fi
DEF_BRIDGE_COUNT=0; DEF_BRIDGE_OLDEST=""
if [ -f "$NEXUS_ROOT/state/bridge_sha256.tsv" ]; then
    DEF_BRIDGE_COUNT=$(grep -cvE '^(#|$)' "$NEXUS_ROOT/state/bridge_sha256.tsv" 2>/dev/null || echo 0)
    DEF_BRIDGE_OLDEST=$(grep -vE '^(#|$)' "$NEXUS_ROOT/state/bridge_sha256.tsv" 2>/dev/null | awk -F'\t' '{print $4}' | sort | head -1)
    [ -z "$DEF_BRIDGE_OLDEST" ] && DEF_BRIDGE_OLDEST="-"
fi
DEF_R3_HOOK="no"
if [ -f "$NEXUS_ROOT/.githooks/pre-commit" ] && grep -q "R3 full\|R3-full\|r3_full" "$NEXUS_ROOT/.githooks/pre-commit" 2>/dev/null; then
    DEF_R3_HOOK="yes"
fi
DEF_R4_ROT=0
if [ -f "$NEXUS_ROOT/state/falsifier_registry_rotation_log.jsonl" ]; then
    DEF_R4_ROT=$(wc -l < "$NEXUS_ROOT/state/falsifier_registry_rotation_log.jsonl" | tr -d ' ')
fi
echo "  R1 falsifier baseline sha:  $DEF_FAL_SHA"
echo "  R1 bridge sha entries:      $DEF_BRIDGE_COUNT (oldest=$DEF_BRIDGE_OLDEST)"
echo "  R3-full pre-commit hook:    $DEF_R3_HOOK"
echo "  R4 rotation log entries:    $DEF_R4_ROT"

# ─── 8. timeline status (atlas_health_timeline rotation watch) ───
echo ""
echo "▶ 8. timeline status (atlas_health_timeline.jsonl)"
TL_LINES=0; TL_LAST_ROT="-"
if [ -f "$NEXUS_ROOT/state/atlas_health_timeline.jsonl" ]; then
    TL_LINES=$(wc -l < "$NEXUS_ROOT/state/atlas_health_timeline.jsonl" | tr -d ' ')
fi
if [ -f "$NEXUS_ROOT/state/atlas_health_timeline.rotation.log" ]; then
    TL_LAST_ROT=$(tail -1 "$NEXUS_ROOT/state/atlas_health_timeline.rotation.log" 2>/dev/null | sed -nE 's/.*"ts":"([^"]+)".*/\1/p')
    [ -z "$TL_LAST_ROT" ] && TL_LAST_ROT="-"
fi
echo "  timeline lines:             $TL_LINES"
echo "  last rotation ts:           $TL_LAST_ROT"

# ─── aggregate sentinel ──────────────────────────────────────
echo ""
echo "═════════════════════════════════════════════════════════════"
echo "  SUMMARY"
echo "─────────────────────────────────────────────────────────────"
printf "  hexa runtime:      %s\n" "$([ "$RUNTIME_HEALTHY" = "1" ] && echo "PASS ✅" || echo "FAIL ❌ ($RUNTIME_STATUS)")"
printf "  atlas total facts: %s (across %s shards)\n" "$STATS_TOTAL" "$STATS_SHARDS"
printf "  4-repo Honesty:    %s REPO_INVARIANT\n" "$DASHBOARD_HONESTY"
printf "  4-repo cum facts:  %s\n" "$DASHBOARD_FACTS"
printf "  recent commits:    %s atlas-touching, +%s additions\n" "$DIFF_COMMITS" "$DIFF_ADD"
printf "  staged atlas:      %s entries pending\n" "$PRECOMMIT_STAGED"
printf "  cross-shard:       %s HARMLESS_DUP, %s CONFLICT\n" "$COLLISION_DUP" "$COLLISION_CONF"
printf "  defense R1/R3/R4:  fal_sha=%s bridge=%s r3_hook=%s rotations=%s\n" "$DEF_FAL_SHA" "$DEF_BRIDGE_COUNT" "$DEF_R3_HOOK" "$DEF_R4_ROT"
printf "  timeline:          %s lines (last_rot=%s)\n" "$TL_LINES" "$TL_LAST_ROT"
echo "═════════════════════════════════════════════════════════════"

EXIT_CODE=0
[ "$RUNTIME_HEALTHY" = "0" ] && EXIT_CODE=2
[ "$COLLISION_CONF" -gt 0 ] && EXIT_CODE=2
echo "__ATLAS_STATUS_ALL__ runtime=$RUNTIME_STATUS dashboard_h=$DASHBOARD_HONESTY facts=$STATS_TOTAL shards=$STATS_SHARDS staged_atlas=$PRECOMMIT_STAGED collision_dup=$COLLISION_DUP collision_conflict=$COLLISION_CONF defense_r1_falsifier=$DEF_FAL_SHA defense_r1_bridge=$DEF_BRIDGE_COUNT defense_r3_full=$DEF_R3_HOOK defense_r4_rotations=$DEF_R4_ROT timeline_lines=$TL_LINES timeline_last_rot=$TL_LAST_ROT"
exit $EXIT_CODE
