#!/usr/bin/env bash
# Generate concise markdown status report with clean tables.
set -euo pipefail

NEXUS="${HOME}/Dev/nexus"
OUT="${NEXUS}/shared/QUICK_STATUS.md"

/usr/bin/python3 << 'PYEOF'
import json, os
from datetime import datetime
from collections import Counter

HOME = os.path.expanduser('~')
NX = f'{HOME}/Dev/nexus'
ts = datetime.now().strftime('%Y-%m-%d %H:%M')

# Load data
def count(p):
    try: return sum(1 for _ in open(p))
    except: return 0

closed = count(f'{NX}/shared/verified_constants.jsonl')
topo = count(f'{NX}/shared/cycle/topology.jsonl')
disc = count(f'{NX}/shared/discovery_log.jsonl')
stubs = len(os.listdir(f'{NX}/shared/calc/auto_stubs')) if os.path.isdir(f'{NX}/shared/calc/auto_stubs') else 0

status = Counter()
source_proj = Counter()
for l in open(f'{NX}/shared/verified_constants.jsonl'):
    try:
        j = json.loads(l)
        status[j.get('status','?')] += 1
        source_proj[j.get('project','?')] += 1
    except: pass
exact = status.get('EXACT', 0)
pass_ = status.get('PASS', 0)
fail = status.get('FAIL', 0)
near = status.get('NEAR', 0)

# Project breakdown
domains = Counter()
for i,l in enumerate(open(f'{NX}/shared/cycle/topology.jsonl')):
    if i > 15000: break
    try: domains[json.loads(l).get('domain','?')] += 1
    except: pass

# Milestones
ms_list = [1000, 2500, 5000, 7500, 10000, 20000, 50000, 100000, 200000, 500000, 1000000]
next_ms = next((m for m in ms_list if m > closed), ms_list[-1])
pct_ms = closed * 100 / next_ms

# LaunchAgents count
import subprocess
agents = subprocess.run(['launchctl','list'], capture_output=True, text=True).stdout
agent_lines = [l for l in agents.split('\n') if 'nexus' in l or 'airgenome' in l]

md = f"""# 🛸 NEXUS-6 Quick Status — {ts}

## 📊 핵심 지표

| 지표 | 값 |
|---|---|
| **Total Closed** | {closed:,} |
| **EXACT** | {exact:,} |
| **PASS** | {pass_:,} |
| **NEAR / FAIL** | {near} / {fail} |
| **Topology (Σ)** | {topo:,} |
| **Discovery Log** | {disc:,} |
| **Calc Stubs** | {stubs} |
| **다음 Milestone** | {next_ms//1000}k ({pct_ms:.1f}%) |
| **LaunchAgents** | {len(agent_lines)} |

## 📦 프로젝트별 Topology 흡수

| 프로젝트 | Topology Points | 점유율 |
|---|---:|---:|
"""
total_topo = sum(domains.values()) or 1
for d, c in domains.most_common(10):
    pct = c*100/total_topo
    md += f"| `{d}` | {c:,} | {pct:.1f}% |\n"

md += f"""

## 🎯 Closure 소스별 (Top 10)

| Source | EXACT 기록 수 |
|---|---:|
"""
for p, c in source_proj.most_common(10):
    md += f"| `{p}` | {c:,} |\n"

md += f"""

## ⚙️ 활성 Agents ({len(agent_lines)})

"""
for line in sorted(agent_lines):
    parts = line.strip().split('\t')
    if len(parts) >= 3:
        name = parts[2]
        md += f"- `{name}`\n"

md += f"""

---
*auto-generated by `tools/gen-quick-status.sh` · 10min interval*
"""

with open(f'{NX}/shared/QUICK_STATUS.md', 'w') as f:
    f.write(md)
print(f"[{ts}] quick-status → shared/QUICK_STATUS.md ({len(md)}B)")
PYEOF
